// Activités autorisées (B_06.01.0020) — annexe II du règlement d'exécution (UE) 2024/2956.
// Codes issus du modèle maître de l'EBA (exercice à blanc 2024, liste LIST0601020) :
// à confirmer avec la taxonomie de reporting DORA en vigueur avant l'export XBRL-CSV.
// La valeur stockée est le code EBA (ex. « eba_TA:x163 ») ; « fonctions_de_soutien »
// correspond au cas prévu par le règlement d'une fonction non liée à une activité autorisée.

export const FONCTIONS_DE_SOUTIEN = 'fonctions_de_soutien';

const groupe = (label, items) => ({
  label,
  options: items.map(([code, libelle]) => ({ value: `eba_TA:${code}`, label: libelle })),
});

export const ACTIVITES_AUTORISEES = [
  {
    label: 'Cas général',
    options: [{ value: FONCTIONS_DE_SOUTIEN, label: "Fonctions de soutien (fonction non liée à une activité autorisée)" }],
  },
  groupe('Établissements de crédit', [
    ['x162', 'Réception de dépôts ou d’autres fonds remboursables'],
    ['x163', 'Prêts'],
    ['x164', 'Crédit-bail'],
    ['x28', 'Services de paiement'],
    ['x165', 'Émission et gestion d’autres moyens de paiement'],
    ['x166', 'Garanties et engagements'],
    ['x167', 'Garanties et engagements liés au prêt et à l’emprunt de titres (point 6 de l’annexe I de la directive 2013/36/UE)'],
    ['x168', 'Transactions pour compte propre ou pour compte de la clientèle'],
    ['x169', 'Participation aux émissions de titres et prestation de services afférents'],
    ['x170', 'Services de conseil'],
    ['x171', 'Intermédiation sur les marchés interbancaires'],
    ['x172', 'Gestion ou conseil en gestion de patrimoine'],
    ['x174', 'Conservation et administration de valeurs mobilières'],
    ['x178', 'Location de coffres-forts'],
    ['x179', 'Services de renseignements commerciaux'],
    ['x104', 'Services de change'],
  ]),
  groupe('Services et activités d’investissement', [
    ['x133', 'Réception et transmission d’ordres'],
    ['x134', 'Exécution d’ordres pour le compte de clients'],
    ['x173', 'Négociation pour compte propre'],
    ['x136', 'Gestion de portefeuille'],
    ['x137', 'Conseil en investissement'],
    ['x138', 'Prise ferme et/ou placement d’instruments financiers avec engagement ferme'],
    ['x139', 'Placement d’instruments financiers sans engagement ferme'],
    ['x140', 'Exploitation d’un MTF (système multilatéral de négociation)'],
    ['x141', 'Exploitation d’un OTF (système organisé de négociation)'],
    ['x175', 'Conservation et administration d’instruments financiers pour le compte de clients'],
    ['x143', 'Octroi de crédits ou de prêts à un investisseur'],
    ['x144', 'Conseil aux entreprises en structure du capital, stratégie industrielle, fusions et rachats'],
    ['x146', 'Recherche en investissements et analyse financière'],
    ['x147', 'Services liés à la prise ferme'],
    ['x204', 'Services d’investissement liés au sous-jacent des instruments dérivés'],
    ['x230', 'Exploitation d’un marché réglementé'],
  ]),
  groupe('Paiement et monnaie électronique', [
    ['x220', 'Versement d’espèces sur un compte de paiement et opérations de gestion du compte'],
    ['x221', 'Retrait d’espèces sur un compte de paiement et opérations de gestion du compte'],
    ['x222', 'Exécution d’opérations de paiement, y compris les transferts de fonds sur un compte de paiement'],
    ['x223', 'Exécution d’opérations de paiement couvertes par une ligne de crédit'],
    ['x224', 'Émission d’instruments de paiement et/ou acquisition d’opérations de paiement'],
    ['x225', 'Transmission de fonds'],
    ['x226', 'Services d’initiation de paiement'],
    ['x227', 'Services d’information sur les comptes'],
    ['x180', 'Émission de monnaie électronique'],
  ]),
  groupe('Crypto-actifs', [
    ['x228', 'Conservation et administration de crypto-actifs pour le compte de clients'],
    ['x229', 'Exploitation d’une plateforme de négociation de crypto-actifs'],
    ['x231', 'Échange de crypto-actifs contre des fonds'],
    ['x232', 'Échange de crypto-actifs contre d’autres crypto-actifs'],
    ['x233', 'Exécution d’ordres sur crypto-actifs pour le compte de clients'],
    ['x234', 'Placement de crypto-actifs'],
    ['x181', 'Réception et transmission d’ordres sur crypto-actifs pour le compte de clients'],
    ['x235', 'Conseil en crypto-actifs'],
    ['x182', 'Gestion de portefeuille de crypto-actifs'],
    ['x236', 'Services de transfert de crypto-actifs pour le compte de clients'],
    ['x237', 'Émission de jetons se référant à un ou des actifs'],
  ]),
  groupe('Assurance non-vie', [
    ['x185', 'Branches 1 et 2 : accidents et maladie'],
    ['x186', 'Branches 1 (4e tiret), 3, 7 et 10 : automobile'],
    ['x187', 'Branches 1 (4e tiret), 4, 6, 7 et 12 : maritime et transport'],
    ['x188', 'Branches 1 (4e tiret), 5, 7 et 11 : aviation'],
    ['x189', 'Branches 8 et 9 : incendie et autres dommages aux biens'],
    ['x190', 'Branches 10, 11, 12 et 13 : responsabilité civile'],
    ['x191', 'Branches 14 et 15 : crédit et caution'],
    ['x192', 'Toutes branches, au choix des États membres'],
  ]),
  groupe('Assurance vie', [
    ['x193', 'Assurance vie (article 2, paragraphe 3, point a) i), ii) et iii), hors II et III)'],
    ['x194', 'Assurance nuptialité, assurance natalité'],
    ['x195', 'Assurance vie liée à des fonds d’investissement'],
    ['x196', 'Assurance maladie permanente (article 2, paragraphe 3, point a) iv))'],
    ['x197', 'Tontines (article 2, paragraphe 3, point b) i))'],
    ['x198', 'Opérations de capitalisation (article 2, paragraphe 3, point b) ii))'],
    ['x199', 'Gestion de fonds collectifs de retraite (article 2, paragraphe 3, point b) iii) et iv))'],
    ['x200', 'Opérations visées à l’article 2, paragraphe 3, point b) v)'],
    ['x201', 'Opérations visées à l’article 2, paragraphe 3, point c)'],
  ]),
  groupe('Distribution d’assurance et retraite professionnelle', [
    ['x202', 'Distribution d’assurances'],
    ['x203', 'Distribution de réassurances'],
    ['x205', 'Opérations de retraite professionnelle et activités qui en découlent'],
  ]),
  groupe('Gestion d’actifs (OPCVM et FIA)', [
    ['x183', 'Gestion de portefeuilles d’investissement (directive FIA)'],
    ['x184', 'Gestion de portefeuilles d’investissement (directive OPCVM)'],
    ['x176', 'Conservation et administration de parts d’organismes de placement collectif'],
    ['x177', 'Services non essentiels : conservation et administration de parts d’OPC'],
    ['x259', 'Interposition entre contreparties'],
    ['x260', 'Gestion des risques'],
    ['x261', 'Services juridiques et de comptabilité du fonds'],
    ['x262', 'Demandes de renseignements des clients'],
    ['x263', 'Évaluation et fixation des prix, y compris les déclarations fiscales'],
    ['x264', 'Contrôle du respect des obligations réglementaires'],
    ['x265', 'Tenue du registre des porteurs de parts / actionnaires'],
    ['x266', 'Émissions et rachats de parts / d’actions'],
    ['x267', 'Tenue du registre des porteurs de parts'],
    ['x268', 'Émissions et rachats de parts'],
    ['x269', 'Règlement des contrats (y compris envoi des certificats)'],
    ['x270', 'Distribution des revenus'],
    ['x271', 'Enregistrement et conservation des opérations'],
    ['x272', 'Commercialisation'],
    ['x273', 'Services nécessaires aux obligations fiduciaires du gestionnaire de FIA'],
    ['x274', 'Conseil en investissement sur des instruments de l’annexe I, section C, de la directive 2004/39/CE'],
    ['x275', 'Services auxiliaires'],
  ]),
  groupe('Dépositaires centraux de titres', [
    ['x238', 'Service de notaire'],
    ['x239', 'Service de tenue centralisée de comptes'],
    ['x240', 'Service de règlement'],
    ['x241', 'Organisation d’un mécanisme de prêt de titres entre participants d’un système de règlement'],
    ['x242', 'Services de gestion des garanties'],
    ['x243', 'Services généraux de gestion des garanties'],
    ['x244', 'Établissement de liens entre DCT, tenue de comptes titres liée au règlement, aux garanties et autres services'],
    ['x245', 'Rapprochement des instructions, routage, confirmation et vérification des transactions'],
    ['x246', 'Services liés aux registres d’actionnaires'],
    ['x247', 'Traitement des opérations sur titres (fiscalité, assemblées générales, information)'],
    ['x248', 'Services de nouvelles émissions, dont attribution et gestion des codes ISIN'],
    ['x249', 'Routage et traitement des instructions, perception des frais et déclarations associées'],
    ['x250', 'Déclarations réglementaires'],
    ['x251', 'Fourniture d’informations, de données et de statistiques à des organismes publics ou intergouvernementaux'],
    ['x252', 'Fourniture de services informatiques'],
    ['x253', 'Ouverture de comptes en espèces et acceptation de dépôts des participants (point 1 de l’annexe I de la directive 2013/36/UE)'],
    ['x254', 'Crédit en espèces remboursable au plus tard le jour ouvrable suivant et prêt de titres (point 2 de l’annexe I de la directive 2013/36/UE)'],
    ['x255', 'Services de paiement liés aux espèces et aux opérations de change (point 4 de l’annexe I de la directive 2013/36/UE)'],
    ['x256', 'Activités de trésorerie en devises et en valeurs mobilières liées à la gestion des soldes créditeurs des participants'],
    ['x257', 'Autres services accessoires de type non bancaire autorisés par l’autorité nationale (CSDR, section B)'],
    ['x258', 'Autres services accessoires de type bancaire autorisés par l’autorité nationale (CSDR, section C)'],
  ]),
  groupe('Référentiels, notation, indices et communication de données', [
    ['x214', 'Collecte et conservation des enregistrements de dérivés (hors opérations de financement sur titres)'],
    ['x215', 'Collecte et conservation des enregistrements d’opérations de financement sur titres'],
    ['x216', 'Collecte et conservation des enregistrements de titrisations'],
    ['x212', 'Services accessoires hors titrisation'],
    ['x213', 'Services accessoires de titrisation'],
    ['x206', 'Émission de notations de crédit'],
    ['x207', 'Administration des dispositifs de détermination d’un indice de référence'],
    ['x208', 'Collecte, analyse ou traitement des données sous-jacentes d’un indice de référence'],
    ['x209', 'Détermination d’un indice de référence par formule, méthode de calcul ou évaluation des données'],
    ['x210', 'Publication d’un indice de référence'],
    ['x217', 'Activité de dispositif de publication agréé (APA)'],
    ['x218', 'Activité de fournisseur de système consolidé de publication (CTP)'],
    ['x219', 'Activité de mécanisme de déclaration agréé (ARM)'],
    ['x211', 'Fourniture de services de financement participatif'],
  ]),
];

// Liste à plat : code -> libellé
export const LIBELLES_ACTIVITES = Object.fromEntries(
  ACTIVITES_AUTORISEES.flatMap((g) => g.options.map((o) => [o.value, o.label])),
);
